scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.3
        max_y: 0.2
        max_z: 0.5
        min_x: -0.3
        min_y: -0.2
        min_z: -0.5
        
        invert: false # 激活以移除框外的所有点,不激活以移除框内的所有点
