/ira_merger_node:
  ros__parameters:
    destination_frame: "base_link"
    cloud_destination_topic: "/merged_cloud"
    scan_destination_topic: "/scan_multi"
    laserscan_topics: /scan_up/scan /scan_down/scan
    angle_min: -3.14
    angle_max: 3.14
    angle_increment: 0.00437
    scan_time: 0.0
    range_min: 0.1
    range_max: 2.0


