/mycar_lkw_4w_1/mini_driver: #增加命名空间
# /**: #或者直接设置为/**表示该命名空间下的所有节点,匹配
  ros__parameters: 
    base_frame: base_footprint1
    baud_rate: 115200
    control_rate: 50 # (int)(1000 / control_rate_)建议使用10的倍数,最好为50
    encoder_resolution: 44.0
    kd: 130
    ki: 0
    kp: 100
    maximum_encoding: 100.0
    model_param_acw: 0.45
    model_param_cw: 0.45
    odom_frame: odom1
    port_name: /dev/mycar
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    reduction_ratio: 90.0
    use_sim_time: false
    wheel_diameter: 0.080
