mycar_driver_cpp:
  ros__parameters:
    port: "/dev/mycar"
    baud_rate: 115200
    data_bits: 8
    odom_frame: "odom"
    odom_topic: "/odom"
    imu_frame: "imu"
    imu_topic: "/imu"
    wheel_diameter: 0.0325 #车轮半径 单位米 0.065 / 2
    wheel_distance: 0.21 #车轮间距
    cmd_vel_timeout: 0.1 #速度指令超时时间,单位秒
    cmd_vel_timer_frequency: 10.0 #速度指令定时器频率,单位Hz
    reduction_ratio: 90.0 #减速比
    encoder_resolution: 44 #编码器分辨率
    max_velocity: 100 #电机速度的最值,单位为 编码器计数/pid周期
    kp: 300 #PID控制器的比例增益
    ki: 0 #PID控制器的积分增益
    kd: 200 #PID控制器的微分增益
    voltage_topic: "/battery_voltage" #电压话题名称
  